import "@/styles/globals.css";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "XD Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return children;
}
